/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ICeikFMPoolInterface extends ethers.utils.Interface {
  functions: {
    "swapToCFM()": FunctionFragment;
    "swapToKlay(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "swapToCFM", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapToKlay",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "swapToCFM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapToKlay", data: BytesLike): Result;

  events: {
    "SwapToCFM(address,uint256)": EventFragment;
    "SwapToKlay(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SwapToCFM"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapToKlay"): EventFragment;
}

export class ICeikFMPool extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ICeikFMPoolInterface;

  functions: {
    swapToCFM(overrides?: PayableOverrides): Promise<ContractTransaction>;

    "swapToCFM()"(overrides?: PayableOverrides): Promise<ContractTransaction>;

    swapToKlay(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "swapToKlay(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  swapToCFM(overrides?: PayableOverrides): Promise<ContractTransaction>;

  "swapToCFM()"(overrides?: PayableOverrides): Promise<ContractTransaction>;

  swapToKlay(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "swapToKlay(uint256)"(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    swapToCFM(overrides?: CallOverrides): Promise<void>;

    "swapToCFM()"(overrides?: CallOverrides): Promise<void>;

    swapToKlay(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "swapToKlay(uint256)"(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    SwapToCFM(user: string | null, amount: null): EventFilter;

    SwapToKlay(user: string | null, amount: null): EventFilter;
  };

  estimateGas: {
    swapToCFM(overrides?: PayableOverrides): Promise<BigNumber>;

    "swapToCFM()"(overrides?: PayableOverrides): Promise<BigNumber>;

    swapToKlay(amount: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "swapToKlay(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    swapToCFM(overrides?: PayableOverrides): Promise<PopulatedTransaction>;

    "swapToCFM()"(overrides?: PayableOverrides): Promise<PopulatedTransaction>;

    swapToKlay(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "swapToKlay(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
