/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ArkInterface extends ethers.utils.Interface {
  functions: {
    "record()": FunctionFragment;
    "receiveNew()": FunctionFragment;
    "total()": FunctionFragment;
    "users(uint256)": FunctionFragment;
    "records(address)": FunctionFragment;
    "withdrawNew()": FunctionFragment;
    "newceik()": FunctionFragment;
    "usersCount()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "owner()": FunctionFragment;
    "isOwner()": FunctionFragment;
    "setNewceik(address)": FunctionFragment;
    "oldceik()": FunctionFragment;
    "received(address)": FunctionFragment;
    "step()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "setStep(uint256)": FunctionFragment;
    "withdrawOld()": FunctionFragment;
    "sendOld()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "record", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiveNew",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "total", values?: undefined): string;
  encodeFunctionData(functionFragment: "users", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "records", values: [string]): string;
  encodeFunctionData(
    functionFragment: "withdrawNew",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "newceik", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usersCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "setNewceik", values: [string]): string;
  encodeFunctionData(functionFragment: "oldceik", values?: undefined): string;
  encodeFunctionData(functionFragment: "received", values: [string]): string;
  encodeFunctionData(functionFragment: "step", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setStep",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawOld",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sendOld", values?: undefined): string;

  decodeFunctionResult(functionFragment: "record", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "receiveNew", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "total", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawNew",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newceik", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usersCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setNewceik", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oldceik", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "received", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "step", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setStep", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawOld",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sendOld", data: BytesLike): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class Ark extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ArkInterface;

  functions: {
    record(overrides?: Overrides): Promise<ContractTransaction>;

    "record()"(overrides?: Overrides): Promise<ContractTransaction>;

    receiveNew(overrides?: Overrides): Promise<ContractTransaction>;

    "receiveNew()"(overrides?: Overrides): Promise<ContractTransaction>;

    total(overrides?: CallOverrides): Promise<[BigNumber]>;

    "total()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    users(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    "users(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    records(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "records(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdrawNew(overrides?: Overrides): Promise<ContractTransaction>;

    "withdrawNew()"(overrides?: Overrides): Promise<ContractTransaction>;

    newceik(overrides?: CallOverrides): Promise<[string]>;

    "newceik()"(overrides?: CallOverrides): Promise<[string]>;

    usersCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    "usersCount()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    isOwner(overrides?: CallOverrides): Promise<[boolean]>;

    "isOwner()"(overrides?: CallOverrides): Promise<[boolean]>;

    setNewceik(
      _newceik: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setNewceik(address)"(
      _newceik: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    oldceik(overrides?: CallOverrides): Promise<[string]>;

    "oldceik()"(overrides?: CallOverrides): Promise<[string]>;

    received(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "received(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    step(overrides?: CallOverrides): Promise<[BigNumber]>;

    "step()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setStep(
      _step: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setStep(uint256)"(
      _step: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdrawOld(overrides?: Overrides): Promise<ContractTransaction>;

    "withdrawOld()"(overrides?: Overrides): Promise<ContractTransaction>;

    sendOld(overrides?: Overrides): Promise<ContractTransaction>;

    "sendOld()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  record(overrides?: Overrides): Promise<ContractTransaction>;

  "record()"(overrides?: Overrides): Promise<ContractTransaction>;

  receiveNew(overrides?: Overrides): Promise<ContractTransaction>;

  "receiveNew()"(overrides?: Overrides): Promise<ContractTransaction>;

  total(overrides?: CallOverrides): Promise<BigNumber>;

  "total()"(overrides?: CallOverrides): Promise<BigNumber>;

  users(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "users(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  records(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "records(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawNew(overrides?: Overrides): Promise<ContractTransaction>;

  "withdrawNew()"(overrides?: Overrides): Promise<ContractTransaction>;

  newceik(overrides?: CallOverrides): Promise<string>;

  "newceik()"(overrides?: CallOverrides): Promise<string>;

  usersCount(overrides?: CallOverrides): Promise<BigNumber>;

  "usersCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  isOwner(overrides?: CallOverrides): Promise<boolean>;

  "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

  setNewceik(
    _newceik: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setNewceik(address)"(
    _newceik: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  oldceik(overrides?: CallOverrides): Promise<string>;

  "oldceik()"(overrides?: CallOverrides): Promise<string>;

  received(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "received(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  step(overrides?: CallOverrides): Promise<BigNumber>;

  "step()"(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setStep(
    _step: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setStep(uint256)"(
    _step: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdrawOld(overrides?: Overrides): Promise<ContractTransaction>;

  "withdrawOld()"(overrides?: Overrides): Promise<ContractTransaction>;

  sendOld(overrides?: Overrides): Promise<ContractTransaction>;

  "sendOld()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    record(overrides?: CallOverrides): Promise<void>;

    "record()"(overrides?: CallOverrides): Promise<void>;

    receiveNew(overrides?: CallOverrides): Promise<void>;

    "receiveNew()"(overrides?: CallOverrides): Promise<void>;

    total(overrides?: CallOverrides): Promise<BigNumber>;

    "total()"(overrides?: CallOverrides): Promise<BigNumber>;

    users(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "users(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    records(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "records(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawNew(overrides?: CallOverrides): Promise<void>;

    "withdrawNew()"(overrides?: CallOverrides): Promise<void>;

    newceik(overrides?: CallOverrides): Promise<string>;

    "newceik()"(overrides?: CallOverrides): Promise<string>;

    usersCount(overrides?: CallOverrides): Promise<BigNumber>;

    "usersCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    isOwner(overrides?: CallOverrides): Promise<boolean>;

    "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

    setNewceik(_newceik: string, overrides?: CallOverrides): Promise<void>;

    "setNewceik(address)"(
      _newceik: string,
      overrides?: CallOverrides
    ): Promise<void>;

    oldceik(overrides?: CallOverrides): Promise<string>;

    "oldceik()"(overrides?: CallOverrides): Promise<string>;

    received(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "received(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    step(overrides?: CallOverrides): Promise<BigNumber>;

    "step()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setStep(_step: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "setStep(uint256)"(
      _step: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawOld(overrides?: CallOverrides): Promise<void>;

    "withdrawOld()"(overrides?: CallOverrides): Promise<void>;

    sendOld(overrides?: CallOverrides): Promise<void>;

    "sendOld()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    record(overrides?: Overrides): Promise<BigNumber>;

    "record()"(overrides?: Overrides): Promise<BigNumber>;

    receiveNew(overrides?: Overrides): Promise<BigNumber>;

    "receiveNew()"(overrides?: Overrides): Promise<BigNumber>;

    total(overrides?: CallOverrides): Promise<BigNumber>;

    "total()"(overrides?: CallOverrides): Promise<BigNumber>;

    users(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "users(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    records(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "records(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawNew(overrides?: Overrides): Promise<BigNumber>;

    "withdrawNew()"(overrides?: Overrides): Promise<BigNumber>;

    newceik(overrides?: CallOverrides): Promise<BigNumber>;

    "newceik()"(overrides?: CallOverrides): Promise<BigNumber>;

    usersCount(overrides?: CallOverrides): Promise<BigNumber>;

    "usersCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    isOwner(overrides?: CallOverrides): Promise<BigNumber>;

    "isOwner()"(overrides?: CallOverrides): Promise<BigNumber>;

    setNewceik(_newceik: string, overrides?: Overrides): Promise<BigNumber>;

    "setNewceik(address)"(
      _newceik: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    oldceik(overrides?: CallOverrides): Promise<BigNumber>;

    "oldceik()"(overrides?: CallOverrides): Promise<BigNumber>;

    received(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "received(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    step(overrides?: CallOverrides): Promise<BigNumber>;

    "step()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setStep(_step: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "setStep(uint256)"(
      _step: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdrawOld(overrides?: Overrides): Promise<BigNumber>;

    "withdrawOld()"(overrides?: Overrides): Promise<BigNumber>;

    sendOld(overrides?: Overrides): Promise<BigNumber>;

    "sendOld()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    record(overrides?: Overrides): Promise<PopulatedTransaction>;

    "record()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    receiveNew(overrides?: Overrides): Promise<PopulatedTransaction>;

    "receiveNew()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    total(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "total()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    users(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "users(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    records(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "records(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawNew(overrides?: Overrides): Promise<PopulatedTransaction>;

    "withdrawNew()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    newceik(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "newceik()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    usersCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "usersCount()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setNewceik(
      _newceik: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setNewceik(address)"(
      _newceik: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    oldceik(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "oldceik()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    received(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "received(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    step(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "step()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setStep(
      _step: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setStep(uint256)"(
      _step: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdrawOld(overrides?: Overrides): Promise<PopulatedTransaction>;

    "withdrawOld()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    sendOld(overrides?: Overrides): Promise<PopulatedTransaction>;

    "sendOld()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
